apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfs-sep-helm-repo
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
