apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1d
  targetNamespace: metallb-system
  chart:
    spec:
      chart: metallb
      version: '0.1.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami-helm-repo
        namespace: flux-system
      interval: 1d
  values:
    fullnameOverride: metallb

    ## Metallb Controller deployment.
    ## ref: https://hub.docker.com/r/metallb/controller/tags
    controller:
      image:
        registry: docker.io
        repository: metallb/controller
        tag: v0.9
        pullPolicy: IfNotPresent

    ## Metallb Speaker daemonset.
    ## ref: https://hub.docker.com/r/metallb/speaker/tags
    speaker:
      image:
        registry: docker.io
        repository: metallb/speaker
        tag: v0.9
        pullPolicy: IfNotPresent

    configInline:
      # The address-pools section lists the IP addresses that MetalLB is
      # allowed to allocate, along with settings for how to advertise
      # those addresses over BGP once assigned. You can have as many
      # address pools as you want.
      address-pools:
      - # A name for the address pool. Services can request allocation
        # from a specific address pool using this name, by listing this
        # name under the 'metallb.universe.tf/address-pool' annotation.
        name: generic-cluster-pool
        # Protocol can be used to select how the announcement is done.
        # Supported values are bgp and layer2.
        protocol: layer2
        # A list of IP address ranges over which MetalLB has
        # authority. You can list multiple ranges in a single pool, they
        # will all share the same settings. Each range can be either a
        # CIDR prefix, or an explicit start-end range of IPs.
        addresses:
        - 192.168.88.100-192.168.88.150
