apiVersion: v1
kind: Namespace
metadata:
  name: storage
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-provisioner
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: storage
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '4.0.x'
      sourceRef:
        kind: HelmRepository
        name: nfs-sep-helm-repo
        namespace: flux-system
      interval: 24h
  values:
    fullnameOverride: nfs-subdir-provisioner
    nfs:
      server: 192.168.88.246
      path: /data/kubernetes
    storageClass:
      onDelete: retain
      pathPattern: ${.PVC.namespace}-${.PVC.name}
      defaultClass: true
