apiVersion: v1
kind: Namespace
metadata:
  name: storage
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: flux-system
spec:
  interval: 1d
  targetNamespace: storage
  chart:
    spec:
      chart: nfs-client-provisioner
      version: '1.3.x'
      sourceRef:
        kind: HelmRepository
        name: moikot-helm-repo
        namespace: flux-system
      interval: 1d
  values:
    fullnameOverride: nfs-client-provisioner
    image:
      repository: moikot/nfs-subdir-external-provisioner-arm
      tag: v1
    nfs:
      server: 192.168.88.246
      path: /data/kubernetes
    storageClass:
      reclaimPolicy: Retain
      defaultClass: true
      appendVolumeName: false
